const tickets = [
  {
    id: 11,
    from_email: "glorialim.dev@gmail.com",
    customer_name: "Gloria",
    title: "Shipping with Shopify",
    created_at: "2024-04-23T00:33:56.262Z",
    updated_at: "2024-04-23T00:33:56.262Z",
    agent_id: 2,
    status_id: 1,
    conversations: [
      {
        id: 28,
        ticket_id: 11,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>Do I need to ship items myself?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.270Z",
        updated_at: "2024-04-23T00:33:56.270Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 2,
      full_name: "Sebastian varon",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 10,
    from_email: "glorialim.dev@gmail.com",
    customer_name: "Gloria",
    title: "Available Currencies",
    created_at: "2024-04-23T00:33:56.241Z",
    updated_at: "2024-04-23T00:33:56.241Z",
    agent_id: 3,
    status_id: 1,
    conversations: [
      {
        id: 27,
        ticket_id: 10,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>What currencies does Shopify work with?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.248Z",
        updated_at: "2024-04-23T00:33:56.248Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 3,
      full_name: "Gloria Lim",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 9,
    from_email: "santiago@walker-ryan.example",
    customer_name: "Miss Horace Walker",
    title: "Receiving Order Question",
    created_at: "2024-04-23T00:33:56.217Z",
    updated_at: "2024-04-23T00:33:56.217Z",
    agent_id: 1,
    status_id: 1,
    conversations: [
      {
        id: 26,
        ticket_id: 9,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>What happens when I receive an order?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.226Z",
        updated_at: "2024-04-23T00:33:56.226Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 1,
      full_name: "Triage",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 8,
    from_email: "vanetta@lynch.test",
    customer_name: "Barbera Hills",
    title: "Getting Started Question",
    created_at: "2024-04-23T00:33:56.187Z",
    updated_at: "2024-04-23T00:33:56.187Z",
    agent_id: 1,
    status_id: 1,
    conversations: [
      {
        id: 25,
        ticket_id: 8,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>What do I need to start selling on Shopify?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.197Z",
        updated_at: "2024-04-23T00:33:56.197Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 1,
      full_name: "Triage",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 7,
    from_email: "daria@ferry.test",
    customer_name: "Lashon Lang",
    title: "Domain Name Question",
    created_at: "2024-04-23T00:33:56.165Z",
    updated_at: "2024-04-23T00:33:56.165Z",
    agent_id: 1,
    status_id: 1,
    conversations: [
      {
        id: 24,
        ticket_id: 7,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>Can I use my own domain name with Shopify?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.173Z",
        updated_at: "2024-04-23T00:33:56.173Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 1,
      full_name: "Triage",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 6,
    from_email: "marcos_crist@smitham.test",
    customer_name: "Sen. Ward Mante",
    title: "Dropshipping Question",
    created_at: "2024-04-23T00:33:56.134Z",
    updated_at: "2024-04-23T00:33:56.134Z",
    agent_id: 1,
    status_id: 1,
    conversations: [
      {
        id: 23,
        ticket_id: 6,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>What is dropshipping, and how can I dropship with Shopify?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.143Z",
        updated_at: "2024-04-23T00:33:56.143Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 1,
      full_name: "Triage",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 5,
    from_email: "brande.dooley@reinger.test",
    customer_name: "Ima Klein",
    title: "Getting started with Shopify Question",
    created_at: "2024-04-23T00:33:56.105Z",
    updated_at: "2024-04-23T00:33:56.105Z",
    agent_id: 3,
    status_id: 1,
    conversations: [
      {
        id: 22,
        ticket_id: 5,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>Do I need to be a designer or developer to use Shopify?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.118Z",
        updated_at: "2024-04-23T00:33:56.118Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 3,
      full_name: "Gloria Lim",
    },
    status: {
      description: "Open",
    },
  },
  {
    id: 4,
    from_email: "alesha.lesch@gutmann-donnelly.test",
    customer_name: "Devin Schmeler CPA",
    title: "Cancel Subscription ",
    created_at: "2024-04-23T00:33:56.029Z",
    updated_at: "2024-04-23T19:51:33.998Z",
    agent_id: 3,
    status_id: 2,
    conversations: [
      {
        id: 21,
        ticket_id: 4,
        body: "<p>Hello,</p><p><br></p><p>Your service has been cancelled. If you need any further assistance, feel free to reach out to us.</p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:56.088Z",
        updated_at: "2024-04-23T00:33:56.088Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 20,
        ticket_id: 4,
        body: "Thanks for your help. I appreciate it.",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.078Z",
        updated_at: "2024-04-23T00:33:56.078Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 19,
        ticket_id: 4,
        body: "<p>Hello,</p><p><br></p><p>I am sorry to hear that. I will cancel the service for you.</p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:56.066Z",
        updated_at: "2024-04-23T00:33:56.066Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 18,
        ticket_id: 4,
        body: "I am not satisfied with the service. I would like to cancel it.",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.058Z",
        updated_at: "2024-04-23T00:33:56.058Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 17,
        ticket_id: 4,
        body: "<p>Hello,</p><p><br></p><p>Sure, may I know the reason for the cancellation?</p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:56.048Z",
        updated_at: "2024-04-23T00:33:56.048Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 16,
        ticket_id: 4,
        body: "Hey, I would like to cancel the service. Can you help me with that?",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.038Z",
        updated_at: "2024-04-23T00:33:56.038Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 3,
      full_name: "Gloria Lim",
    },
    status: {
      description: "Answered",
    },
  },
  {
    id: 3,
    from_email: "inger@herman-heaney.test",
    customer_name: "Nicolas Williamson",
    title: "Facebook Ads Help",
    created_at: "2024-04-23T00:33:55.951Z",
    updated_at: "2024-04-23T00:33:55.951Z",
    agent_id: 2,
    status_id: 2,
    conversations: [
      {
        id: 15,
        ticket_id: 3,
        body: "<p>Hello,</p><p><br></p><p>I have made the changes and your ads should be running smoothly now.</p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:56.013Z",
        updated_at: "2024-04-23T00:33:56.013Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 14,
        ticket_id: 3,
        body: "Thank you for your help.",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.004Z",
        updated_at: "2024-04-23T00:33:56.004Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 13,
        ticket_id: 3,
        body: "<p>Hello,</p><p><br></p><p>I have reviewed your social media accounts and the problem may be with your budget. I will make some changes and get back to you.</p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:55.986Z",
        updated_at: "2024-04-23T00:33:55.986Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 12,
        ticket_id: 3,
        body: "Thanks I will be waiting for your response.",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.978Z",
        updated_at: "2024-04-23T00:33:55.978Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 11,
        ticket_id: 3,
        body: "<p>Hello,</p><p><br></p><p>Sure, I can help you with that. Let me take a look at your social media accounts and get back to you. </p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:55.969Z",
        updated_at: "2024-04-23T00:33:55.969Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 10,
        ticket_id: 3,
        body: "I am reaching out to get some help with setting up Facebook ads. Can you help me with that?",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.959Z",
        updated_at: "2024-04-23T00:33:55.959Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 2,
      full_name: "Sebastian varon",
    },
    status: {
      description: "Answered",
    },
  },
  {
    id: 2,
    from_email: "marcel@olson-marvin.example",
    customer_name: "Mariann Graham",
    title: "Social Media Visibility Help",
    created_at: "2024-04-23T00:33:55.700Z",
    updated_at: "2024-04-23T00:33:55.700Z",
    agent_id: 1,
    status_id: 2,
    conversations: [
      {
        id: 9,
        ticket_id: 2,
        body: "thank you for your help",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.933Z",
        updated_at: "2024-04-23T00:33:55.933Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 8,
        ticket_id: 2,
        body: "I have reviewed your social media accounts and have some recommendations for you. The team will implement them shortly.",
        from_customer: false,
        created_at: "2024-04-23T00:33:55.913Z",
        updated_at: "2024-04-23T00:33:55.913Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 7,
        ticket_id: 2,
        body: "Thanks I will be waiting for your response.",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.893Z",
        updated_at: "2024-04-23T00:33:55.893Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 6,
        ticket_id: 2,
        body: "Sure, I can help you with that. Let me take a look at your social media accounts and get back to you.",
        from_customer: false,
        created_at: "2024-04-23T00:33:55.831Z",
        updated_at: "2024-04-23T00:33:55.927Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [
          {
            url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6NCwicHVyIjoiYmxvYl9pZCJ9fQ==--9bce2d7559cc0b333204d5e56e3e58d69b11e6d4/placeholder.jpg",
            filename: "placeholder.jpg",
          },
        ],
      },
      {
        id: 5,
        ticket_id: 2,
        body: "<p>Hi,</p><p><br></p><p>I am reaching out to get some help with increasing my social media visibility. Can you help me with that?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.736Z",
        updated_at: "2024-04-23T00:33:55.864Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [
          {
            url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MywicHVyIjoiYmxvYl9pZCJ9fQ==--7fb2afae0772b49ed9cbc7c5c1ed0bb2d93cb2e2/placeholder.jpg",
            filename: "placeholder.jpg",
          },
        ],
      },
    ],
    agent: {
      id: 1,
      full_name: "Triage",
    },
    status: {
      description: "Answered",
    },
  },
  {
    id: 1,
    from_email: "garland@mitchell.example",
    customer_name: "Long Gerlach",
    title: "Website Traffic Help",
    created_at: "2024-04-23T00:33:55.315Z",
    updated_at: "2024-04-23T00:33:55.315Z",
    agent_id: 3,
    status_id: 2,
    conversations: [
      {
        id: 4,
        ticket_id: 1,
        body: "Thank you for your help. I appreciate it.",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.675Z",
        updated_at: "2024-04-23T00:33:55.675Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 3,
        ticket_id: 1,
        body: "<p>Hello,</p><p><br></p><p>I have identified the issue and it has been resolved. Your website traffic should be back to normal now.</p><p><br></p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:55.657Z",
        updated_at: "2024-04-23T00:33:55.657Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 2,
        ticket_id: 1,
        body: "<p>Hello,</p><p><br></p><p>Let me check the issue and get back to you.</p><p><br></p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:55.596Z",
        updated_at: "2024-04-23T00:33:55.791Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [
          {
            url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MiwicHVyIjoiYmxvYl9pZCJ9fQ==--d20a1b1ff209f428554c889256dfe0956532c79f/placeholder.jpg",
            filename: "placeholder.jpg",
          },
        ],
      },
      {
        id: 1,
        ticket_id: 1,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>I am touching base to let you know that I am experiencing a significant drop in website traffic.</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:55.353Z",
        updated_at: "2024-04-23T00:33:55.785Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [
          {
            url: "http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoiYmxvYl9pZCJ9fQ==--b3a0a54e936ca9d93ba2b433a97d621c03892bea/placeholder.jpg",
            filename: "placeholder.jpg",
          },
        ],
      },
    ],
    agent: {
      id: 3,
      full_name: "Gloria Lim",
    },
    status: {
      description: "Answered",
    },
  },
  {
    id: 32,
    from_email: "adam_walter@bergstrom.test",
    customer_name: "Kenyetta Harber",
    title: "Alias vel recusandae.",
    created_at: "2024-04-23T00:33:56.851Z",
    updated_at: "2024-04-23T00:33:56.851Z",
    agent_id: 7,
    status_id: 3,
    conversations: [],
    agent: {
      id: 7,
      full_name: "Brian Johns",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 31,
    from_email: "kina_farrell@kutch.example",
    customer_name: "Sen. Donnie Fritsch",
    title: "Fuga sequi error.",
    created_at: "2024-04-23T00:33:56.838Z",
    updated_at: "2024-04-23T00:33:56.838Z",
    agent_id: 5,
    status_id: 3,
    conversations: [],
    agent: {
      id: 5,
      full_name: "Norris Erdman",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 30,
    from_email: "mimi@willms-doyle.test",
    customer_name: "Otis Becker",
    title: "Magni et quidem.",
    created_at: "2024-04-23T00:33:56.822Z",
    updated_at: "2024-04-23T00:33:56.822Z",
    agent_id: 7,
    status_id: 3,
    conversations: [],
    agent: {
      id: 7,
      full_name: "Brian Johns",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 29,
    from_email: "gil@hackett.test",
    customer_name: "Kraig Conroy",
    title: "Nihil laboriosam quod.",
    created_at: "2024-04-23T00:33:56.808Z",
    updated_at: "2024-04-23T00:33:56.808Z",
    agent_id: 6,
    status_id: 3,
    conversations: [],
    agent: {
      id: 6,
      full_name: "Ms. Colin Monahan",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 28,
    from_email: "adolfo@kessler.test",
    customer_name: "Mathew Toy",
    title: "Fuga tempora excepturi.",
    created_at: "2024-04-23T00:33:56.793Z",
    updated_at: "2024-04-23T00:33:56.793Z",
    agent_id: 5,
    status_id: 3,
    conversations: [],
    agent: {
      id: 5,
      full_name: "Norris Erdman",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 27,
    from_email: "mohammad@graham.test",
    customer_name: "Mr. Magen Welch",
    title: "Nobis natus et.",
    created_at: "2024-04-23T00:33:56.777Z",
    updated_at: "2024-04-23T00:33:56.777Z",
    agent_id: 10,
    status_id: 3,
    conversations: [],
    agent: {
      id: 10,
      full_name: "Dr. Pa Mueller",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 26,
    from_email: "noah.jacobs@oconnell.test",
    customer_name: "Ismael Casper",
    title: "Veritatis perspiciatis ea.",
    created_at: "2024-04-23T00:33:56.761Z",
    updated_at: "2024-04-23T00:33:56.761Z",
    agent_id: 9,
    status_id: 3,
    conversations: [],
    agent: {
      id: 9,
      full_name: "Miguel Sanford",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 25,
    from_email: "art@corwin.example",
    customer_name: "Mr. Dick Dicki",
    title: "Et et non.",
    created_at: "2024-04-23T00:33:56.744Z",
    updated_at: "2024-04-23T00:33:56.744Z",
    agent_id: 10,
    status_id: 3,
    conversations: [],
    agent: {
      id: 10,
      full_name: "Dr. Pa Mueller",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 24,
    from_email: "alvin.volkman@legros-casper.example",
    customer_name: "Mitsue Considine IV",
    title: "Fugiat eum numquam.",
    created_at: "2024-04-23T00:33:56.730Z",
    updated_at: "2024-04-23T00:33:56.730Z",
    agent_id: 4,
    status_id: 3,
    conversations: [],
    agent: {
      id: 4,
      full_name: "Carroll Ratke JD",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 23,
    from_email: "teddy_effertz@rempel-dickens.test",
    customer_name: "Sen. Logan Thiel",
    title: "Quasi impedit quo.",
    created_at: "2024-04-23T00:33:56.716Z",
    updated_at: "2024-04-23T00:33:56.716Z",
    agent_id: 6,
    status_id: 3,
    conversations: [],
    agent: {
      id: 6,
      full_name: "Ms. Colin Monahan",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 22,
    from_email: "andrew@schimmel.example",
    customer_name: "Missy Kessler MD",
    title: "Sed esse veritatis.",
    created_at: "2024-04-23T00:33:56.703Z",
    updated_at: "2024-04-23T00:33:56.703Z",
    agent_id: 7,
    status_id: 3,
    conversations: [],
    agent: {
      id: 7,
      full_name: "Brian Johns",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 21,
    from_email: "melvin.weissnat@jones.test",
    customer_name: "Beatriz O'Conner",
    title: "Dolor ratione est.",
    created_at: "2024-04-23T00:33:56.690Z",
    updated_at: "2024-04-23T00:33:56.690Z",
    agent_id: 4,
    status_id: 3,
    conversations: [],
    agent: {
      id: 4,
      full_name: "Carroll Ratke JD",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 20,
    from_email: "theressa_welch@cartwright.test",
    customer_name: "Lani Kulas",
    title: "Porro consequatur in.",
    created_at: "2024-04-23T00:33:56.677Z",
    updated_at: "2024-04-23T00:33:56.677Z",
    agent_id: 4,
    status_id: 3,
    conversations: [],
    agent: {
      id: 4,
      full_name: "Carroll Ratke JD",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 19,
    from_email: "aubrey@johnston.example",
    customer_name: "Amb. Julius Murray",
    title: "Quo animi laudantium.",
    created_at: "2024-04-23T00:33:56.664Z",
    updated_at: "2024-04-23T00:33:56.664Z",
    agent_id: 10,
    status_id: 3,
    conversations: [],
    agent: {
      id: 10,
      full_name: "Dr. Pa Mueller",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 18,
    from_email: "rodolfo@hintz-robel.example",
    customer_name: "Lilli Vandervort",
    title: "Beatae autem ea.",
    created_at: "2024-04-23T00:33:56.651Z",
    updated_at: "2024-04-23T00:33:56.651Z",
    agent_id: 4,
    status_id: 3,
    conversations: [],
    agent: {
      id: 4,
      full_name: "Carroll Ratke JD",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 17,
    from_email: "hilma.breitenberg@howell-wisozk.test",
    customer_name: "Odell Adams",
    title: "Laborum explicabo beatae.",
    created_at: "2024-04-23T00:33:56.637Z",
    updated_at: "2024-04-23T00:33:56.637Z",
    agent_id: 6,
    status_id: 3,
    conversations: [],
    agent: {
      id: 6,
      full_name: "Ms. Colin Monahan",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 16,
    from_email: "whitney.haley@bradtke.test",
    customer_name: "Delma Turcotte",
    title: "Culpa iste aut.",
    created_at: "2024-04-23T00:33:56.624Z",
    updated_at: "2024-04-23T00:33:56.624Z",
    agent_id: 7,
    status_id: 3,
    conversations: [],
    agent: {
      id: 7,
      full_name: "Brian Johns",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 15,
    from_email: "irving_cremin@davis.test",
    customer_name: "Geoffrey Kuvalis",
    title: "Nam cumque aut.",
    created_at: "2024-04-23T00:33:56.611Z",
    updated_at: "2024-04-23T00:33:56.611Z",
    agent_id: 7,
    status_id: 3,
    conversations: [],
    agent: {
      id: 7,
      full_name: "Brian Johns",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 14,
    from_email: "tamra_grimes@harber-bartell.example",
    customer_name: "Henry Anderson",
    title: "Laborum qui voluptates.",
    created_at: "2024-04-23T00:33:56.591Z",
    updated_at: "2024-04-23T00:33:56.591Z",
    agent_id: 6,
    status_id: 3,
    conversations: [],
    agent: {
      id: 6,
      full_name: "Ms. Colin Monahan",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 13,
    from_email: "carley@mertz-toy.test",
    customer_name: "Kurtis Crist",
    title: "Cum dignissimos temporibus.",
    created_at: "2024-04-23T00:33:56.511Z",
    updated_at: "2024-04-23T00:33:56.511Z",
    agent_id: 6,
    status_id: 3,
    conversations: [],
    agent: {
      id: 6,
      full_name: "Ms. Colin Monahan",
    },
    status: {
      description: "Resolved",
    },
  },
  {
    id: 12,
    from_email: "walker@cartwright.example",
    customer_name: "Prof. Almeda Koss",
    title: "Third-party payment processor",
    created_at: "2024-04-23T00:33:56.289Z",
    updated_at: "2024-04-23T19:46:43.615Z",
    agent_id: 2,
    status_id: 3,
    conversations: [
      {
        id: 30,
        ticket_id: 12,
        body: "<p>Hello,</p><p><br></p><p>A third-party payment processor (also knows as a payment provider or&nbsp;<a href='https://www.shopify.com/ca/payment-gateways' rel='noopener noreferrer' target='_blank'>payment gateway</a>) lets you accept online payments.</p><p><br></p><p>Let me know if you have any further questions.</p><p><br></p><p>Regards,</p><p><br></p><p><strong>SmartAgent</strong></p><p>Customer Support</p><p><a href='mailto:smartagents3@gmail.com' rel='noopener noreferrer' target='_blank'>smartagents3@gmail.com</a></p>",
        from_customer: false,
        created_at: "2024-04-23T00:33:56.309Z",
        updated_at: "2024-04-23T00:33:56.309Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
      {
        id: 29,
        ticket_id: 12,
        body: "<p>Hi SmartAgent,</p><p><br></p><p>What is a third-party payment processor?</p><p><br></p><p>Thanks.</p>",
        from_customer: true,
        created_at: "2024-04-23T00:33:56.297Z",
        updated_at: "2024-04-23T00:33:56.297Z",
        agent_id: null,
        agent_name: null,
        attachments_urls: [],
      },
    ],
    agent: {
      id: 2,
      full_name: "Sebastian varon",
    },
    status: {
      description: "Resolved",
    },
  },
];
